### ISSUE TITLE
Errro

### ISSUE THREAD

**Issue by llPushkarSinghll** [MHIGists/RPGLike#16]
[Mon_Sep_6-01.35.35-UTC_2021.log](https://github.com/MHIGists/RPGLike/files/7112812/Mon_Sep_6-01.35.35-UTC_2021.log)

**Comment by MHIGists** [comment]
> [Mon_Sep_6-01.35.35-UTC_2021.log](https://github.com/MHIGists/RPGLike/files/7112812/Mon_Sep_6-01.35.35-UTC_2021.log)

Hello,
Thank you for the error log, this has been fixed. However there are more errors to work out. Stay tuned for a release!
