### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by physiciancoder** [MHIGists/RPGLike#17]
Add PM4 support

**Comment by MHIGists** [comment]
> 
> 
> Add PM4 support


Sorry I haven't been active in the PM community what is PM4 exactly?

**Comment by physiciancoder** [comment]
API 4.0.0

**Comment by MHIGists** [comment]
> 
> 
> API 4.0.0

Sure thing i'll look it up!

**Comment by MHIGists** [comment]
The branch has been added! I'll start testing it tomorrow.
