### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AirLeMineral** [MHIGists/RPGLike#9]
PocketMine-MP Crash Dump Tue Aug 4 09:23:56 WIB 2020

Error: Cannot serialize Server instance
File: src/pocketmine/Server
Line: 2472
Type: BadMethodCallException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: RPGLike v0.0.1

Code:
[2463] 		}
[2464] 	}
[2465] 
[2466] 	/**
[2467] 	 * Called when something attempts to serialize the server instance.
[2468] 	 *
[2469] 	 * @throws \BadMethodCallException because Server instances cannot be serialized
[2470] 	 */
[2471] 	public function __sleep(){
[2472] 		throw new \BadMethodCallException("Cannot serialize Server instance");
[2473] 	}
[2474] }

Backtrace:
#0 (): pocketmine\Server->__sleep()
#1 src/pocketmine/utils/Config(229): yaml_emit(array[3], integer 1)
#2 plugins/RPGLike-master/src/TheClimbing/RPGLike/Players/RPGPlayer(260): pocketmine\utils\Config->save()
#3 plugins/RPGLike-master/src/TheClimbing/RPGLike/EventListener(89): TheClimbing\RPGLike\Players\RPGPlayer->savePlayerVariables()
#4 src/pocketmine/plugin/MethodEventExecutor(42): TheClimbing\RPGLike\EventListener->onLeave(object pocketmine\event\player\PlayerQuitEvent)
#5 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object TheClimbing\RPGLike\EventListener, object pocketmine\event\player\PlayerQuitEvent)
#6 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent)
#7 src/pocketmine/Player(3635): pocketmine\event\Event->call()
#8 src/pocketmine/network/mcpe/RakLibInterface(122): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[7] timeout)
#9 vendor/pocketmine/raklib/src/server/ServerHandler(131): pocketmine\network\mcpe\RakLibInterface->closeSession(string[17] 192.168.1.4 57022, string[7] timeout)
#10 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
#11 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
#12 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
#13 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
#14 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1596507836.2291)
#15 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#16 src/pocketmine/Server(1588): pocketmine\Server->start()
#17 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[44] C:\Users\Galih\Desktop\PocketMine-MP-3.12.6\, string[52] C:\Users\Galih\Desktop\PocketMine-MP-3.12.6\plugins\)
#18 src/pocketmine/PocketMine(304): pocketmine\server()
#19 (11): require(string[99] phar://C:/Users/Mineral/Desktop/PocketMine-MP-3.12.6/PocketMine-MP.phar/src/pocket)

PocketMine-MP version: 3.14.1 [Protocol 407]

If the player dies, it cannot respawn and must reload the game. when the player reloads the game, the server crashes.

screenshoot
https://www.dropbox.com/s/4ltioebqmptctsl/Screenshot%202020-08-04%2009.46.58.png?dl=0

**Comment by MHIGists** [comment]
Thank you once again
